services:
  database:
    image: postgres
    container_name: camp-mingle-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camp-mingle-app
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb
    depends_on:
      - database
    ports:
      - '1337:1337'

volumes:
  postgres_data:
